theme: jekyll-theme-cayman

#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Beerer

# Short bio or description (displayed in the header)
Project developed during the workshop GTCWD (Google Technologies for Cloud and Web Development)

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  github: barryclark/jekyll-now
  twitter: jekyllrb

