# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Beerer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beerer
  pod 'pop', '1.0.10'
  pod 'Pages'
  pod 'Firebase/Core'

end
