# Uncomment the next line to define a global platform for your project
platform :ios, "11.0"

target "Beerer" do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beerer
  pod "Hero"
  pod "pop"
  pod "SwiftyJSON"
  pod "Alamofire"
  pod "Firebase/Core"
  pod "Firebase/Auth"
  pod "Cosmos"
end
